---
abstract: 'input messages from Freeswitch.'
author:
  - 'Tomas (t0m) Doran <bobtfish@bobtfish.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: agpl_3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Message::Passing::Input::Freeswitch
name: Message-Passing-Input-Freeswitch
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  ESL: 0
  Message::Passing: 0.006
  Moose: 0
  Task::Weaken: 0
  Try::Tiny: 0
  namespace::autoclean: 0
version: 0.004
